package com.AluraChallenge.ConversorMonedas;

import java.util.Map;

public class CodigosMonedas {
    public static final Map<String, String> codigosMonedas= Map.ofEntries(
                Map.entry("AED","Dírham de los Emiratos Árabes Unidos"),
                Map.entry("ARS","Peso argentino"),
                Map.entry("AUD","Dolar australiano"),
                Map.entry("BOB", "boliviano"),
                Map.entry("BRL","Real brasileño"),
                Map.entry("CAD", "Dolar canadiense"),
                Map.entry("CHF","Franco suizo"),
                Map.entry("CLP", "Peso chileno"),
                Map.entry("COP","Peso colombiano"),
                Map.entry("CNY","Yuan chino"),
                Map.entry("EUR","Euro"),
                Map.entry("MXN","Peso mexicano"),
                Map.entry("NOK", "Corona noruega"),
                Map.entry("QAR","Rial catarí"),
                Map.entry("RUB","Rublo ruso"),
                Map.entry("SAR","Rial saudí"),
                Map.entry("SEK", "Corona sueca"),
                Map.entry("SGD", "Dólar de Singapur"),
                Map.entry("TRY", "Lira turca"),
                Map.entry("USD","Dólar estadounidense"),
                Map.entry("UYU", "Peso uruguayo"),
                Map.entry("VED","Bolívar venezolano"),
                Map.entry("DKK","Corona danesa"),
                Map.entry("JPY","Yen japonés"),
                Map.entry("GBP","Libra esterlina"),
                Map.entry("HKD","Dólar de Hong Kong"),
                Map.entry("KRW","Won coreano"),
                Map.entry("INR","Rupia india"),
                Map.entry("NZD","Dólar neozelandés"),
                Map.entry("ZAR","Rand sudafricano"),
                Map.entry("THB","Baht tailandés"),
                Map.entry("ILS","Nuevo séquel israelí"),
                Map.entry("IDR","Rupia indonesia"),
                Map.entry("PLN","Esloti polaco")

            );

    public static final Map<String, String> codigosLocales= Map.ofEntries(
            Map.entry("AED","en-AE"),
            Map.entry("ARS","es-AR"),
            Map.entry("AUD","en-AU"),
            Map.entry("BOB", "es-BO"),
            Map.entry("BRL","pt-BR"),
            Map.entry("CAD", "en-CA"),
            Map.entry("CHF","de-CH"),
            Map.entry("CLP", "es-CL"),
            Map.entry("COP","es-CO"),
            Map.entry("CNY","zh-CN"),
            Map.entry("EUR","de-DE"),
            Map.entry("MXN","es-MX"),
            Map.entry("NOK", "no-NO"),
            Map.entry("QAR","en-QA"),
            Map.entry("RUB","ru-RU"),
            Map.entry("SAR","en-SA"),
            Map.entry("SEK", "sv-SE"),
            Map.entry("SGD", "zh-SG"),
            Map.entry("TRY", "tr-TR"),
            Map.entry("USD","en-US"),
            Map.entry("UYU", "es-UY"),
            Map.entry("VED","es-VE"),
            Map.entry("DKK","da-DK"),
            Map.entry("JPY","ja-JP"),
            Map.entry("GBP","en-GB"),
            Map.entry("HKD","zh-HK"),
            Map.entry("KRW","ko-KR"),
            Map.entry("INR","en-IN"),
            Map.entry("NZD","en-NZ"),
            Map.entry("ZAR","en-ZA"),
            Map.entry("THB","th-TH"),
            Map.entry("ILS","he-IL"),
            Map.entry("IDR","en-ID"),
            Map.entry("PLN","pl-PL")
    );

}
